export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  PROFILE: "/profile",
  PROFILE_SESSIONS_PASSEES: "/profile/sessions-passees",
  PROFILE_SESSION_DETAIL: "/profile/session/:id",
  ADMIN: "/admin",
  ADMIN_USERS: "/admin/users",
  ADMIN_SESSIONS: "/admin/sessions",
  ADMIN_SESSION_DETAIL: "/admin/sessions/:id",
  ADMIN_FORMATIONS: "/admin/formations",
  ADMIN_CATEGORIES: "/admin/categories",
  FORMATEUR: "/formateur",
  FORMATEUR_SESSIONS: "/formateur/sessions",
  FORMATEUR_SESSION_DETAIL: "/formateur/sessions/:id",
  FORMATEUR_FORMATIONS: "/formateur/formations",
  USER_FORMATIONS: "/profile/formations",
  CATALOGUE: "/catalogue",
  ABOUT: "/about",
  PANIER: "/panier",
  FORMATION_DETAIL: "/formation/:id",
  CONFIDENTIALITE: "/confidentialite",
  ABOUT_US: "/AboutUs",
  DASHBOARD: "/dashboard",
};
